#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Jonas Thyssen
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.dotfiles/prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.dotfiles/prezto/init.zsh"
fi

# Source
source "${ZDOTDIR:-$HOME}/.dotfiles/zsh/plugins/alias-tips/alias-tips.plugin.zsh"

# Configure alias-tips
export ZSH_PLUGINS_ALIAS_TIPS_TEXT="Du har et alias: "

# Enable autosuggestions automatically.
# zle-line-init() {
#     zle autosuggest-start
# }
# zle -N zle-line-init

# Python virtualenvwarpper
export WORKON_HOME="$HOME/.virtualenvs"
export PROJECT_HOME=$HOME/projects
source /usr/local/bin/virtualenvwrapper.sh

# Gulp alias
alias gulp="node_modules/.bin/gulp"